### PR TITLE
feat: add `use_graphics_for` for cleaner boot

### PR DESCRIPTION
**Pull request by vfosterm**

### CODE REVIEW

**Comment by ameoverflow** [comment]
Tested on Arch Linux, and works great. On Windows however, Windows/OEM logo disappears, and spinner has a black box around it (probably Windows issue not rEFInd or theme issue)

**Comment by sgoudham** [comment]
As noted by @nolemretaWxd who tested this on linux and windows, it seems like these changes don't look the greatest on windows. 

I've made a small change to exclude `windows` from the list passed into the `use_graphics_for` field, along with a small explanation why. 

If the issues on windows are not resolvable via this port, I'll merge it in!

**Comment by syndrizzle** [comment]
> Tested on Arch Linux, and works great. On Windows however, Windows/OEM logo disappears, and spinner has a black box around it (probably Windows issue not rEFInd or theme issue)

The windows logo doesn't disappear for me, when using use_graphics_for setting

**Review by sgoudham — APPROVED** [review]
I've just added a note that this option may cause issues and they might be able to fix it by removing their system from the `use_graphics_for` list. 

Thanks for testing, merging it now!

**Pull request merged**
