### PR TITLE
Add systemd icons

### PR DESCRIPTION
**Pull request by Samasaur1**
These icons were created by taking the systemd logomark (available at <https://brand.systemd.io>) and doing the following:
- resizing to match other catppuccin-rEFInd items
- coloring to match other catppuccin-rEFInd items

Since the original logomark is licensed under CC-BY-SA 4.0, these modified versions are also licensed under CC-By-SA 4.0

### CODE REVIEW

**Comment by fapfaff** [comment]
Thanks, it looks great, but the colors don't seem to be a little bit off:
Latte: #4d4f69 instead of #4c4f69
Frappe: #cdd6f4 instead of #c6d0f5
Macchiato: #cdd6f4 instead of #cad3f5

**Comment by Samasaur1** [comment]
> Thanks, it looks great, but the colors don't seem to be a little bit off:
> Latte: #4d4f69 instead of #4c4f69
> Frappe: #cdd6f4 instead of #c6d0f5
> Macchiato: #cdd6f4 instead of #cad3f5

Fixed! I tried to match colors using the eyedropper tool, but I guess it didn't work. These new versions of the image are colored directly from the SVG and converted to PNGs with ImageMagick, so they should be correct.

**Comment by fapfaff** [comment]
Weird, using a color picker I still get different colors as result

**Comment by fapfaff** [comment]
The R and G value seem to be 1 too low for every image

**Comment by Samasaur1** [comment]
Huh, I'm not sure what to do about that — I already tried my best strategy for getting the colors exactly right. I'll leave this PR open in case anyone wants to fix the colors on these icons

**Comment by fapfaff** [comment]
Thank you anyways. I fixed it now.
fyi I used Inkscape to change the color and export it to a pdf

**Pull request closed without merging**
